In [3]:
import tensorflow as tf
print(tf.__version__)

2.1.0


Rank 0 Tensor

In [5]:
tf.Variable("Hello World!", tf.string)
tf.Variable(100.5)
tf.constant([1,2,3,4],shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

Rank 1 Tensor : Numpy Arrays 

In [9]:
float_var= tf.Variable([10.55,11.55], tf.float32,name = "float" )
int_var= tf.Variable([1,2,3], tf.int64)
print("{0},{1}".format(float_var,int_var))

<tf.Variable 'float:0' shape=(2,) dtype=float32, numpy=array([10.55, 11.55], dtype=float32)>,<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>


Rank 2 Tensors: Matrix

In [12]:
float_var = tf.Variable([[19.99,15.55],[14,12]], shape=(2,2))
print("{0}".format(float_var))

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[19.99, 15.55],
       [14.  , 12.  ]], dtype=float32)>
